name: Trigger Jenkins

on:
  push:
    branches:
    - mvn-repo 

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Trigger Jenkins Job
      run: curl -I -u jenkins:${{ secrets.jenkins }} https://jenkins.cofomo.io/job/COFOMO-DISCOVERY/build?token=0sujsKUjkuU1ZGG55ARhLe8uyf&cause=Merged%20into%20master%20branch%20on%20GitHub
