name: Build and Deploy

on:
  push:
    branches:
    - mvn-repo
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.13
      uses: actions/setup-java@v1
      with:
        java-version: 1.13
    - name: Deploy with Maven
      run: mvn clean deploy --file pom.xml
    - name: Trigger Jenkins Job
      run: curl -I -u jenkins:${{ secrets.jenkins }} https://jenkins.cofomo.io/job/COFOMO-DISCOVERY/build?token=0sujsKUjkuU1ZGG55ARhLe8uyf&cause=Merged%20into%20master%20branch%20on%20GitHub
